language: python
sudo: false
dist: trusty
cache:
  directories:
  - $HOME/.cache/pip
python:
- '3.6'
env:
  global:
  - SPHINXINTL_TRANSIFEX_USERNAME=sphinxjp
  - SPHINXINTL_TRANSIFEX_PROJECT_NAME=sphinx-doc-1_6
  - secure: JknT9RYcghlU4OFmUxoTPlm55ENOcM9ebDKCiXeMN/v4heXm+J0FW+V5ubxOXEaN8nAKfFWssKGUyVKpKovIPvCRF8YOKnGdlzWOi/+L2dUyJbsXU3ocYXTAuw2ZO97SVLE9VJ+cMtcRJ/orPJs0spR4RrxOvPYFqnLOlKEL0H7g0MGbJDajOr+GI95I1A+qLkny23WH9q4WnkoUMcVVuP0PF5dkf1Kfxzn82KvnVf/wBO9T6/g5AFNkJaY0NOSjBUfXFtyuLAo9eCZxskYPTcqBtjsDooqpwrXYDFejr8B0dELYxVBNXj1XxwDt93/gJ6qjtxZXhE32LGisatTNzFyvpoEKfBkGsmJunaBXOh/qh4riDILS4jRU3yQJDGLZymoJLVrvJIJe1bV3bhKz+XXHGUVYfrlu5R3LDLaf69JYpVXK2L5Qzmq7batT7Sd20ttEEu6282v4d6nIWVoqysjmCwBboY6sqpcKHEPBM/xPWH7YoRXjFCT8SwZBRsiTYRKqBevWZ//5hsVAkEw7eUrzjxSIoaP71iZJkZYup98U4DeJlgfusOhd8VcP45SAf1QoTNs50Q08zCIhEC7VfWyi9JRjsFeMKaQDiwM17VUEwVyhIWUuxHfmM9NVQWwDb/lciKw8P8B+3zZTTWce7TV4cdLs9M+x6uQrlOggCgk=
install:
- pip install -U pip setuptools
script:
- ls sphinx
- (cd sphinx && git checkout master)
- pip install -r ./locale/requirements.txt
- sphinx-intl create-transifexrc
- cd locale
- rm -R pot
- sphinx-build -b gettext ../sphinx/doc pot
- sphinx-intl update-txconfig-resources -p pot -d .
- rm -R es ja pt_BR
- tx pull -l es,ja,pt_BR
- git checkout .tx/config
- git add locale
- git commit -am "update"
- git push origin master
